2021-12-05 19:41:14,748 ERROR: Exception on /user/jay [GET] [in /home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/main_app/routes.py", line 80, in user
    return render_template("user.html", params=locals())
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/main_app/templates/user.html", line 12, in template
    {% comment %} {% if params.user == current_user %} {% endcomment %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'comment'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2021-12-05 19:41:14,895 ERROR: Exception on /user/jay [GET] [in /home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/main_app/routes.py", line 80, in user
    return render_template("user.html", params=locals())
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/main_app/templates/user.html", line 12, in template
    {% comment %} {% if params.user == current_user %} {% endcomment %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'comment'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2021-12-05 19:41:15,046 ERROR: Exception on /user/jay [GET] [in /home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/main_app/routes.py", line 80, in user
    return render_template("user.html", params=locals())
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/main_app/templates/user.html", line 12, in template
    {% comment %} {% if params.user == current_user %} {% endcomment %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'comment'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2021-12-05 19:42:01,395 INFO: Microblog startup [in /home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/main_app/__init__.py:37]
